name: Checks

on: [push, pull_request]

# For a more complex build matrix example see:
# https://github.com/evandroforks/anki/blob/master/.github/workflows/checks.yml
jobs:

  test:
    name: Unit Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [1.8, 1.11]

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify
