name: Checks

on: [push, pull_request]

# For a more complex build matrix example see:
# https://github.com/evandroforks/anki/blob/master/.github/workflows/checks.yml
jobs:

  test:
    name: Tests on ${{ matrix.os }} JDK ${{ matrix.java }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [1.8, 1.11]

      # Keep all systems running if something fails
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Automatically format and commit code with Google style guide
      # https://github.com/axel-op/googlejavaformat-action/issues/4
      - uses: axel-op/googlejavaformat-action@v3
        if: matrix.java == '1.11' && matrix.os == 'ubuntu-latest'
        with:
          args: "--skip-sorting-imports --replace"

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify
